USE AMS
GO

SELECT COLUMN_NAME, Data_type, CHARACTER_MAXIMUM_LENGTH, numeric_precision, NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS	
WHERE TABLE_NAME = 'tbShiftDeposit'

SELECT COLUMN_NAME, Data_type, CHARACTER_MAXIMUM_LENGTH, numeric_precision, NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS	
WHERE TABLE_NAME = 'tbshift'


SELECT COLUMN_NAME, Data_type, 
	Case WHEN Data_TYPE = 'varchar' THEN CAST (CHARACTER_MAXIMUM_LENGTH as char(5))
	ELSE  CAST (NUMERIC_PRECISION as varchar(5)) + ',' + CAST( NUMERIC_SCALE AS char(5))
		END AS  DT_SIZE
FROM INFORMATION_SCHEMA.COLUMNS	
WHERE TABLE_NAME = 'tbshiftdeposit'





SELECT table_name
FROM information_schema.columns
WHERE Contains (column_name, '%contain%')
ORDER BY table_name desc

SELECT COLUMN_NAME, Data_type, CHARACTER_MAXIMUM_LENGTH, numeric_precision, NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS	
WHERE TABLE_NAME = 'tbtagshipment'